import MainContainer from "@/app/components/mainContainer/layout";

export const metadata = {
  title: "Importand",
  description: "Generated by create next app",
};

export const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <MainContainer>{children}</MainContainer>
    </>
  );
};

export default RootLayout;
