export const metadata = {
  title: "Importand",
  description: "Generated by create next app",
};

export const ImportandLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  return <>{children}</>;
};

export default ImportandLayout;
