export const metadata = {
  title: "My Day",
  description: "Generated by create next app",
};
export default function DayLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
