"use client";
import { useState } from "react";
import "./globals.scss";
import { ContentWrapper } from "./components/content-wrapper/ContentWrapper";
import { Navigation } from "./components/navigation/Navigation";
import { ButtonHome } from "./components/navigation/ButtonHome";
import { ButtonMenu } from "./components/navigation/ButtonMenu";
import { ButtonProfile } from "./components/navigation/profile/ButtonProfile";
import { Groups } from "./components/groups/Groups";
import { ListProjects } from "./components/groups/list-projects/ListProjects";
import { ListMenu } from "./components/groups/list-menu/ListMenu";
import { MainView } from "./components/mainView/MainView";
export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isShownGrouprs, setIsShownGroups] = useState(true);
  const handleClickShownMenu = (e: React.MouseEvent) =>
    setIsShownGroups(!isShownGrouprs);

  return (
    <html lang="en">
      <body>
        <ContentWrapper>
          <Navigation>
            <ButtonHome />
            <ButtonMenu onclick={handleClickShownMenu} />
            <ButtonProfile />
          </Navigation>
          {isShownGrouprs && (
            <Groups>
              <ListMenu />
              <ListProjects />
            </Groups>
          )}
          <MainView>{children}</MainView>
        </ContentWrapper>
      </body>
    </html>
  );
}
