"use client";
import "@/app/globals.scss";
const metadata = {
  title: "Today",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
